### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by jberthe** [mauriciolauffer/ui5-cli-deployer#2]
Hi Mauricio,

I'm interresting on your project, can you explain how to use it ? Maybe it is a stupid question, but I'm new in that "cli" world ;) 

Regards,

**Comment by mauriciolauffer** [comment]
@jberthe sorry for the ultra late response, I've just seen the comment now.

[ui5-cli](https://github.com/SAP/ui5-cli) doesn't support plug-ins nor extensions, therefore I've forked it in this project. This's the CLI base for the project [ui5-deployer](https://github.com/mauriciolauffer/ui5-deployer).

This project is not meant to be consumed by itself nor any other project. But could be used as "inspiration" for similar use cases when people want to add new features to ui5-cli.

**Comment by jberthe** [comment]
Ok, thanks for your answer.
